sudo: false

language: python

cache: pip

python:
    - "2.7"

addons:
    postgresql: "9.4"


before_install:
    - pip install --upgrade pip
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install psycopg2
    - pip install Flask-Restless
    - pip install flask-cors
    - pip install requests
    - pip install DateTime
    - pip install simplejson

install:
    - pip install autopep8
    - pip install coverage
    - pip install pylint

before_script:
    - printenv | sort
    - psql -c 'create database marveldb;' -U postgres
    - psql -c "ALTER USER postgres WITH PASSWORD 'idb';" -U postgres
    
script:
    - python travis_init.py delete
    - uname -a
    - date
    - make test

notifications:
    slack: cs373-ut:NQeMTshj4bAVXnatgGvUaD6j
